services:
  connection-monitor:
    image: smcarlisle/connection-monitor:0.5
    ports:
      - "3000:3000"
    environment:
      HOSTS: 8.8.8.8,google.com,amazon.com
      POLL_RATE: 5 # in seconds
      ALWAYS_ON: true #true : polling runs all the time false: polling only runs when user has UI open
      UNCOMPRESSED_LOG_DAYS: 0 #logs created yesterday or before are archived. 1 keeps yesterday's logs uncompressed...
    volumes:
      - ./docker-logs:/usr/src/app/logs
